# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy_commad.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64ummy_commad.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n\x0c\x44ummyCommand\x12!\n\x0b\x63ommandType\x18\x01 \x01(\x0e\x32\x0c.CommandType\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*;\n\x0b\x43ommandType\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04STOP\x10\x02\x42 \n\x0b\x63om.exampleB\x11\x44ummyCommandProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dummy_commad_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013com.exampleB\021DummyCommandProto'
  _COMMANDTYPE._serialized_start=153
  _COMMANDTYPE._serialized_end=212
  _DUMMYCOMMAND._serialized_start=55
  _DUMMYCOMMAND._serialized_end=151
# @@protoc_insertion_point(module_scope)
